name: agora_rtc_engine
description: >-
  Flutter plugin to simply integrate Agora Video Calling or Live Video Streaming
  to your app with just a few lines of code.
version: 4.2.2
homepage: https://www.agora.io
repository: https://github.com/AgoraIO/Flutter-SDK
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.6'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  json_annotation: ^4.4.0
dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.11.5
  json_serializable: ^6.1.1
flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agora_rtc_engine
        pluginClass: AgoraRtcEnginePlugin
      ios:
        pluginClass: AgoraRtcEnginePlugin
