name: agora_rtc_engine
description: Flutter plugin for Agora Video SDK.
version: 4.0.0-rc.3
homepage: 'https://www.agora.io'
repository: 'https://github.com/AgoraIO/Flutter-SDK'
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.6'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  json_annotation: ^4.0.0
dev_dependencies:
  integration_test: ^1.0.2+2
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  pedantic: ^1.11.0
  build_runner: ^1.11.5
  json_serializable: ^4.0.2
flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agora_rtc_engine
        pluginClass: AgoraRtcEnginePlugin
      ios:
        pluginClass: AgoraRtcEnginePlugin
      linux:
        pluginClass: AgoraRtcEnginePlugin
      macos:
        pluginClass: AgoraRtcEnginePlugin
      windows:
        pluginClass: AgoraRtcEnginePlugin
      web:
        fileName: agora_rtc_engine_web.dart
        pluginClass: AgoraRtcEngineWeb


