name: agora_rtc_engine
description: Flutter plugin for Agora Video SDK.
version: 0.9.1
author: Agora.io
homepage: https://www.agora.io

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: io.agora.agorartcengine
    pluginClass: AgoraRtcEnginePlugin
