name: agora_rtc_engine
description: Flutter plugin for Agora Video SDK.
version: 3.0.20-special.20
homepage: 'https://www.agora.io'
repository: 'https://github.com/AgoraIO/Flutter-SDK'
environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.12.13+hotfix.6'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  json_annotation: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  e2e: ^0.2.1
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0
  build_runner: ^1.7.0
  json_serializable: ^3.2.0
flutter:
  plugin:
    platforms:
      android:
        package: io.agora.agora_rtc_engine
        pluginClass: AgoraRtcEnginePlugin
      ios:
        pluginClass: AgoraRtcEnginePlugin

