name: testcase_gen
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

publish_to: none

dependencies:
  args: ^2.3.1
  dart_style: ^2.2.1

dev_dependencies:
  lints: ^1.0.0
  # lock the version of analyzer to avoid non-consistent generated code and errors like:
  # lib/core/paraphrase.dart:352:53: Error: The getter 'name' isn't defined for the class 'Token'.
  analyzer: 4.7.0
