name: Publish to Pub.dev ğŸš€

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'

jobs:
  publishing:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ format('{0}/{1}/versions/{2}', "https://pub.dev/packages", steps.publish.outputs.package, steps.publish.outputs.remoteVersion) }}
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3
      - name: Check Versions ğŸ”
        run: |
          set -eo pipefail
          export LIB_VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          export PUBSPEC_VERSION=$(grep 'version: ' pubspec.yaml | sed -e 's,.*: \(.*\),\1,')
          if [ "$LIB_VERSION" != "$PUBSPEC_VERSION" ]; then
            echo "Version in 'pubspec.yaml' does not match tag.";
            exit 1;
          fi
      - name: Publish Dart Package ğŸš¢
        id: publish
        uses: k-paxian/dart-package-publisher@1.5
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
