name: 'run: test'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      flutter-versions:
        description: 'Flutter versions to test (JSON array)'
        required: false
        default: '["3.32.5"]'
        type: string
    secrets:
      APP_ID:
        required: true

jobs:
  flutter_codestyle_check:
    name: Flutter codestyle/analyze check
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Check Dart Format
        run: bash ci/dart_pub_publish_check.sh
      - uses: axel-op/dart-package-analyzer@v3
        id: analysis
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Check scores
        env:
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          if (( $TOTAL_MAX - $TOTAL > 10 ))
          then
            echo Pub Score too low.
            exit 1
          fi

  flutter_ut:
    name: Flutter unit test
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter test

  attach_docs:
    name: Attach dartdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Build DartDoc üìñ
        run: |
          dart pub get
          # Generate DartDoc
          dart doc
          # Create a zip file of the DartDoc output
          zip -r agora_rtc_engine_docs.zip doc
      - name: Upload DartDoc Artifact ‚¨ÜÔ∏è
        uses: actions/upload-artifact@v4
        with:
          name: agora_rtc_engine_docs.zip
          path: agora_rtc_engine_docs.zip

  pub_publish_check:
    name: pub publish check
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: bash ci/dart_pub_publish_check.sh

  integration_test_android:
    name: Run Flutter Android Integration Tests (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      TEST_APP_ID: ${{ secrets.APP_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: run flutter android integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: pixel_5
          ram-size: 2048M
          heap-size: 4096M
          disk-size: 8192M
          script: bash ci/run_flutter_integration_test_android.sh

  integration_test_ios:
    name: Run Flutter iOS Integration Tests (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: macos-latest
    timeout-minutes: 120
    env:
      TEST_APP_ID: ${{ secrets.APP_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 15'
      - run: bash ci/run_flutter_integration_test_ios.sh
      - name: Get ios crash logs
        if: always()
        run: |
          sleep 30

          mkdir logs-ios

          CRASH_DIR="${HOME}/Library/Logs/DiagnosticReports/"
          OUTPUT_CRASH_DIR=./logs-ios/crash
          mkdir -p ${OUTPUT_CRASH_DIR}

          # Copy all files
          cp -RP $CRASH_DIR* $OUTPUT_CRASH_DIR || true
        
      - name: Upload ios logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs-ios-${{ matrix.version }}
          path: logs-ios/*

  integration_test_macos:
    name: Run Flutter macOS Integration Tests (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: macos-latest
    timeout-minutes: 120
    env:
      TEST_APP_ID: ${{ secrets.APP_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - run: flutter config --enable-macos-desktop
      - run: bash ci/run_flutter_macos_integration_test.sh
      - name: Get iris logs macos
        if: always()
        run: |
          sleep 30

          mkdir iris-logs-macos
          if [ -f "${HOME}/Library/Containers/com.example.fakeTestApp/Data/Library/agora-iris.log" ]; then
            cp -RP ${HOME}/Library/Containers/com.example.fakeTestApp/Data/Library/agora-iris.log ./iris-logs-macos/agora-iris-fake-test.log || true
          fi
          if [ -f "${HOME}/Library/Containers/com.example.integrationTestApp/Data/Library/agora-iris.log" ]; then
            cp -RP ${HOME}/Library/Containers/com.example.integrationTestApp/Data/Library/agora-iris.log ./iris-logs-macos/agora-iris-integration-test.log || true
          fi

          CRASH_DIR="${HOME}/Library/Logs/DiagnosticReports/"
          OUTPUT_CRASH_DIR=./iris-logs-macos/crash
          mkdir -p ${OUTPUT_CRASH_DIR}

          # Copy all files
          cp -RP $CRASH_DIR* $OUTPUT_CRASH_DIR || true
          
      - name: Upload iris logs macos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: iris-logs-macos-${{ matrix.version }}
          path: iris-logs-macos/*

  integration_test_swiftpm:
    name: Run Flutter SwiftPM Integration Tests (${{ matrix.os }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos", "ios"]
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Run flutter integration test swiftpm for ${{ matrix.os }}
        if: ${{ matrix.os == 'macos' }}
        run: |
          flutter pub get
          flutter build ${{ matrix.os }}
        working-directory: test_shard/integration_test_swiftpm
      - name: Run flutter integration test swiftpm for ${{ matrix.os }}
        if: ${{ matrix.os == 'ios' }}
        run: |
          flutter pub get
          flutter build ${{ matrix.os }} --no-codesign
        working-directory: test_shard/integration_test_swiftpm

  integration_test_windows:
    name: Run Flutter Windows Integration Tests (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: windows-2022
    timeout-minutes: 120
    env:
      TEST_APP_ID: ${{ secrets.APP_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - name: Set up crash dump environment
        run: .\ci\setup-crash-dumps.ps1
        shell: powershell
      - run: flutter config --enable-windows-desktop
      - name: Run windows integration test
        shell: bash
        run: |
          bash ci/run_flutter_windows_integration_test.sh

      - name: Upload crash dumps if exist
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: windows-crash-dumps-${{ matrix.version }}
          path: ./CrashDumps/*

  integration_test_web:
    name: Run Flutter Web Integration Tests (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      TEST_APP_ID: ${{ secrets.APP_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - name: Run web integration test
        shell: bash
        run: |
          chromedriver --port=4444 --trace-buffer-size=100000 &
          bash ci/run_flutter_integration_test_web.sh

  build_android_ubuntu:
    name: Build Android on Ubuntu (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - run: flutter pub get
      - name: Run flutter build apk
        run: flutter build apk
        working-directory: example

  build_android_windows:
    name: Build Android on Windows (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - run: flutter pub get
      - name: Run flutter build apk
        run: flutter build apk
        working-directory: example

  build_ios:
    name: Build iOS (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: macos-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - run: flutter pub get
      - name: Run flutter build ios --no-codesign
        run: flutter build ios --no-codesign
        working-directory: example

  # This job aim to cover https://github.com/flutter/flutter/issues/135739
  build_ios_xcode_15:
    name: Build iOS with xcode 15.x (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: macos-13
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - run: | # https://github.com/actions/runner-images/issues/6746#issuecomment-1380042553
          # set xcode version to use for build
          sudo xcode-select -switch /Applications/Xcode_15.0.1.app
          # Print used xCode version
          xcode-select -print-path
          xcodebuild -version
      - run: flutter pub get
      - name: Run flutter build ios --no-codesign
        run: flutter build ios --no-codesign
        working-directory: example

  build_web:
    name: Build Web (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - run: flutter packages get
      - name: Run flutter build web
        run: flutter build web
        working-directory: example

  rendering_test_android:
    name: Run Flutter Android Rendering Tests
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      TEST_APP_ID: ${{ secrets.APP_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: run flutter android integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 31
          arch: x86_64
          profile: pixel_5
          ram-size: 2048M
          heap-size: 4096M
          disk-size: 8192M
          script: bash ci/rendering_test_android.sh

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-debug-golden-files
          path: test_shard/rendering_test/screenshot/*.debug.png

  rendering_test_ios:
    name: Run Flutter iOS Rendering Tests (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: macos-13 # Rendering test on ios simulator need macos 13+
    timeout-minutes: 60
    env:
      TEST_APP_ID: ${{ secrets.APP_ID }}
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - uses: futureware-tech/simulator-action@v3
        with:
          model: 'iPhone 15'
      - run: bash ci/rendering_test_ios.sh

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ios-debug-golden-files
          path: test_shard/rendering_test/screenshot/*.debug.png

  rendering_test_macos:
    name: Run Flutter macOS Rendering Tests (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: macos-latest
    timeout-minutes: 120
    env:
      TEST_APP_ID: ${{ secrets.APP_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - run: flutter config --enable-macos-desktop
      - name: Run macos rendering test
        run: |
          export SAVE_DEBUG_GOLDEN="true"
          bash ci/rendering_test_macos.sh
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: macos-debug-golden-files
          path: test_shard/rendering_test/screenshot/*.debug.png

  rendering_test_windows:
    name: Run Flutter Windows Rendering Tests (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: windows-2022
    timeout-minutes: 120
    env:
      TEST_APP_ID: ${{ secrets.APP_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - run: flutter config --enable-windows-desktop
      - name: Run windows integration test
        shell: bash
        run: |
          export SAVE_DEBUG_GOLDEN="true"

          bash ci/rendering_test_windows.sh
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: windows-debug-golden-files
          path: test_shard/rendering_test/screenshot/*.debug.png

  rendering_test_web:
    name: Run Flutter Web Rendering Tests (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      TEST_APP_ID: ${{ secrets.APP_ID }}
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - name: Run web rendering test
        shell: bash
        run: |
          export SAVE_DEBUG_GOLDEN="true"

          chromedriver --port=4444 --trace-buffer-size=100000 &
          bash ci/run_rendering_test.sh web

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: web-debug-golden-files
          path: test_shard/rendering_test/screenshot/*.debug.png

  check_android15_16k_page_alignment:
    name: Check android15 16k page size alignment (Flutter ${{ matrix.version }})
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci:skip') }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJSON(inputs.flutter-versions) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ matrix.version }}
          cache: true
      - run: flutter pub get
      - name: Run flutter build apk
        run: flutter build apk
        working-directory: example
      - name: Check android15 16k page size alignment
        run: bash scripts/check_android15_16k_page_alignment.sh example/build/app/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib/arm64-v8a/libiris_rendering_android.so
