# This workflow is aim to let external contributors to run the integration tests.
# * Check if the user is a external or internal contributor or not (who is in the org or not).
# * If the user is a internal contributor, label it with "ci:schedule_run_ci".
# * If the user is a external contributor, remove the label "ci:schedule_run_ci" for each push.
# * The PR with label "ci:schedule_run_ci" can trigger the `workflows/build.yml`.
# 
# If the user is a external contributor, the repo owener or the users with write access should response for add the 
# label "ci:schedule_run_ci" to allow the external contributor to run the CI.
name: Schedule run ci

on:
  pull_request:
    types: [opened, reopened, labeled, synchronize]

jobs:
  check_permission:
    name: Check permission
    runs-on: ubuntu-latest
    timeout-minutes: 60
    outputs:
        is_schedule_run_ci: ${{ steps.check-label-step.outputs.result }}
    steps:
      - name: Check if external contributors
        id: check-contributors-result
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.LABEL_ACTION_PAT }}
          debug: true
          script: |
            const org = "AgoraIO-Extensions"
            const userName = "${{ github.event.pull_request.user.login }}"

            // see https://docs.github.com/en/rest/orgs/members?apiVersion=2022-11-28#check-organization-membership-for-a-user
            const response = await github.request('GET /orgs/{org}/members/{username}', {
                org: org,
                username: userName,
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              })

            if (response.status == 204) {
                console.log(`Internal contributor: ${userName}`);
                console.log(`Add label: ci:schedule_run_ci`);

                const prNumber = ${{ github.event.number }}
                await github.rest.issues.addLabels({
                    issue_number: prNumber,
                    owner: 'AgoraIO-Extensions',
                    repo: 'Agora-Flutter-SDK',
                    labels: ['ci:schedule_run_ci']
                  })
            } else {
                console.log(`Not a internal contributor: ${response.data}`);
            }

            // 0: internal contributors
            // 1: external contributors
            return response.status == 204 ? 0 : 1

      - name: Remove label ci:schedule_run_ci if necessary
        # If the external contributor (1) push a new commit, remove the label: ci:schedule_run_ci
        if: ${{ github.event_name == 'push' && steps.check-contributors-result.outputs.result == 1 }}
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.LABEL_ACTION_PAT }}
          repo: 'AgoraIO-Extensions'
          number: 'Agora-Flutter-SDK'
          labels: ci:schedule_run_ci

      - name: Check if labeled ci:schedule_run_ci
        id: check-label-step
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.LABEL_ACTION_PAT }}
          debug: true
          script: |
            const owner = "AgoraIO-Extensions"
            const repo = 'Agora-Flutter-SDK'
            const prNumber = "${{ github.event.number }}"

            // see https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28
            const response = await github.request('GET /repos/{owner}/{repo}/issues/{issue_number}/labels', {
                owner: owner,
                repo: repo,
                issue_number: prNumber,
                headers: {
                  'X-GitHub-Api-Version': '2022-11-28'
                }
              })

            if (response.status != 200) {
              return 1;
            }

            console.log(`response.data: ${response.data}`);

            const labels = response.data;
            for (let label of labels) {
                let name = label.name
                if ("ci:schedule_run_ci" == name) {
                    console.log(`Found label ci:schedule_run_ci, return.`);
                    return 0;
                }
            }

            return 1;

  schedule_ci:
    name: Schedule run ci
    needs: check_permission
    if: ${{ needs.check_permission.outputs.is_schedule_run_ci == 0 }}
    uses: ./.github/workflows/build.yml
    secrets:
      MY_APP_ID: ${{ secrets.MY_APP_ID }}
            